version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build:
    docker:
      - image: circleci/node:lts
    resource_class: large

    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: fix for broken p4-css
          command: rm -rf node_modules/p4-css
      - run:
          name: Install npm
          command: npm install
      - run:
          name: Node-SASS
          command: npm rebuild node-sass
      - run:
          name: Build
          command: npm run build
      - run:
          name: Test
          command: npm run test
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/coverage-final.json
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
